name: flymenu
main: com.flymenu.flymenu.Plugin
version: 0.1
api-version: 1.15
commands:
  flymenu:
    description: FlyMenu
    permission: flymenu.open
  flyoptions:
    description: FlyOptions Menu
    permission: flymenu.options